<?php

namespace Drupal\course_enrollment\Entity;

use Drupal\Core\Entity\ContentEntityBase;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Defines the Enrollment entity.
 *
 * @ContentEntityType(
 *   id = "enrollment",
 *   label = @Translation("Enrollment"),
 *   label_collection = @Translation("Enrollments"),
 *   label_singular = @Translation("enrollment"),
 *   label_plural = @Translation("enrollments"),
 *   handlers = {
 *     "list_builder" = "Drupal\course_enrollment\EnrollmentListBuilder",
 *     "views_data" = "Drupal\views\EntityViewsData",
 *     "form" = {
 *       "add" = "Drupal\Core\Entity\ContentEntityForm",
 *       "edit" = "Drupal\Core\Entity\ContentEntityForm",
 *       "delete" = "Drupal\Core\Entity\ContentEntityDeleteForm"
 *     },
 *     "route_provider" = {
 *       "html" = "Drupal\Core\Entity\Routing\AdminHtmlRouteProvider"
 *     }
 *   },
 *   base_table = "course_enrollment",
 *   admin_permission = "administer course enrollments",
 *   entity_keys = {
 *     "id" = "id",
 *     "uuid" = "uuid"
 *   },
 *   links = {
 *     "collection" = "/admin/content/enrollments",
 *     "add-form" = "/admin/content/enrollments/add",
 *     "canonical" = "/admin/content/enrollments/{enrollment}",
 *     "edit-form" = "/admin/content/enrollments/{enrollment}/edit",
 *     "delete-form" = "/admin/content/enrollments/{enrollment}/delete"
 *   }
 * )
 */

class Enrollment extends ContentEntityBase {
  
   public function preSave(EntityStorageInterface $storage): void {
    parent::preSave($storage);

    $status = $this->get('status')->value;

    if ($status === 'completed' && $this->get('completed_date')->isEmpty()) {
      $this->set(
        'completed_date',
        \Drupal::time()->getRequestTime(),
      );
    }

    if ($status !== 'completed') {
      $this->set('completed_date', NULL);
    }
  }

  public static function baseFieldDefinitions(EntityTypeInterface $entity_type) {

    $fields = parent::baseFieldDefinitions($entity_type);

    /*
     * Primary ID of the Enrollment.
     */
    $fields['id'] = BaseFieldDefinition::create('integer')
      ->setLabel(new TranslatableMarkup('Enrollment ID'))
      ->setReadOnly(TRUE);

    /*
     * UUID generated by Drupal.
     */
    $fields['uuid'] = BaseFieldDefinition::create('uuid')
      ->setLabel(new TranslatableMarkup('UUID'))
      ->setReadOnly(TRUE);

    /*
     * User who enrolled in the Course.
     */
    $fields['user_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(new TranslatableMarkup('User'))
      ->setDescription(new TranslatableMarkup('The trainee enrolled in the course.'))
      ->setSetting('target_type', 'user')
      ->setRequired(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 0,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    /*
     * Course in which the User is enrolled.
     */
    $fields['course_id'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(new TranslatableMarkup('Course'))
      ->setDescription(new TranslatableMarkup('The course associated with this enrollment.'))
      ->setSetting('target_type', 'node')
      ->setSetting('handler', 'default')
      ->setSetting('handler_settings', [
        'target_bundles' => [
          'course' => 'course',
        ],
      ])
      ->setRequired(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 1,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    /*
     * Current Enrollment status.
     */
    $fields['status'] = BaseFieldDefinition::create('list_string')
      ->setLabel(new TranslatableMarkup('Status'))
      ->setRequired(TRUE)
      ->setSettings([
        'allowed_values' => [
          'enrolled' => new TranslatableMarkup('Enrolled'),
          'completed' => new TranslatableMarkup('Completed'),
        ],
      ])
      ->setDefaultValue('enrolled')
      ->setDisplayOptions('form', [
        'type' => 'options_select',
        'weight' => 2,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayConfigurable('view', TRUE);

    /*
     * Date/time at which enrollment occurred.
     */
    $fields['enrolled_date'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(new TranslatableMarkup('Enrolled date'))
      ->setRequired(TRUE)
      ->setDisplayOptions('view', [
        'type' => 'timestamp',
        'weight' => 3,
      ])
      ->setDisplayConfigurable('view', TRUE);

    /*
     * Date/time at which the Course was completed.
     *
     * Empty while the Enrollment status is "enrolled".
     */
    $fields['completed_date'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(new TranslatableMarkup('Completed date'))
      ->setRequired(FALSE)
      ->setDisplayOptions('view', [
        'type' => 'timestamp',
        'weight' => 4,
      ])
      ->setDisplayConfigurable('view', TRUE);

    /*
     * Entity creation timestamp.
     */
    $fields['created'] = BaseFieldDefinition::create('created')
      ->setLabel(new TranslatableMarkup('Created'));

    /*
     * Entity last-updated timestamp.
     */
    $fields['changed'] = BaseFieldDefinition::create('changed')
      ->setLabel(new TranslatableMarkup('Changed'));

    return $fields;
  }

}